apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-sql
  annotations:
    meta.crossplane.io/maintainer: shahab
    meta.crossplane.io/description: Fully operational PostgreSQL databases in AWS,
    meta.crossplane.io/readme: A Configuration package that defines a SQL and SQLClaim types that can be used to create and provision fully operational databases in AWS
spec:
  crossplane:
    version: ">=v1.15.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-rds
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-sql
      version: ">=v0.9.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.5.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.2.1"
  # - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
  #   version: ">=v0.10.0"
