---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-password
  namespace: crossplane-system
data:
  password: cG9zdGdyZXM=
---
apiVersion: leaseplan.com/v1alpha1
kind: SQL
metadata:
  name: my-db
  annotations:
    organization: lz platform
    author: shahab <shahab.rajaei@leaseplan.com>
spec:
  id: my-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "13"
    size: small
