---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-20240115001654-password
data:
  password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=
---
apiVersion: leaseplan.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
  annotations:
    organization: lz platform
    author: shahab <shahab.rajaei@leaseplan.com>
spec:
  id: my-db-20240115001654
  compositionSelector:
    matchLabels:
      provider: azure
      db: postgresql
  parameters:
    version: "11"
    size: small
    databases:
      - db-01
      - db-02
